"""Patchouli public routes exposed through GlobalSystemBus."""

from hivememory.system.contracts.route_names import RouteNames


class PatchouliRoutes:
    PASSIVE_ANALYZE_AND_RETRIEVE = RouteNames.PATCHOULI_PASSIVE_ANALYZE_AND_RETRIEVE
    SUBMIT_INTERACTION = RouteNames.PATCHOULI_SUBMIT_INTERACTION
    MEMORY_CREATE = RouteNames.PATCHOULI_MEMORY_CREATE
    MEMORY_LIST = RouteNames.PATCHOULI_MEMORY_LIST
    MEMORY_GET = RouteNames.PATCHOULI_MEMORY_GET
    MEMORY_UPDATE = RouteNames.PATCHOULI_MEMORY_UPDATE
    MEMORY_DELETE = RouteNames.PATCHOULI_MEMORY_DELETE
    MEMORY_RECORD_FEEDBACK = RouteNames.PATCHOULI_MEMORY_RECORD_FEEDBACK
    MEMORY_TASK_LIST = RouteNames.PATCHOULI_MEMORY_TASK_LIST
    MEMORY_TASK_GET = RouteNames.PATCHOULI_MEMORY_TASK_GET
    MEMORY_TASK_CANCEL = RouteNames.PATCHOULI_MEMORY_TASK_CANCEL
    AGENT_PROFILE_CREATE = RouteNames.PATCHOULI_AGENT_PROFILE_CREATE
    AGENT_PROFILE_LIST = RouteNames.PATCHOULI_AGENT_PROFILE_LIST
    TOPIC_LIST_ACTIVE = RouteNames.PATCHOULI_TOPIC_LIST_ACTIVE
    MEMORY_RETRIEVE = RouteNames.PATCHOULI_MEMORY_RETRIEVE
    MEMORY_RETRIEVE_BY_ALIASES = RouteNames.PATCHOULI_MEMORY_RETRIEVE_BY_ALIASES
    GET_AGENT_PROFILE = RouteNames.PATCHOULI_GET_AGENT_PROFILE
    PREPARE_AGENT_RUN = RouteNames.PATCHOULI_PREPARE_AGENT_RUN
    FINALIZE_AGENT_RUN = RouteNames.PATCHOULI_FINALIZE_AGENT_RUN
    CLEANUP_PREPARED_AGENT_RUN = RouteNames.PATCHOULI_CLEANUP_PREPARED_AGENT_RUN
    MANUAL_ARCHIVE_TOPIC = RouteNames.PATCHOULI_MANUAL_ARCHIVE_TOPIC
    EVICT_TOPIC = RouteNames.PATCHOULI_EVICT_TOPIC
    RECORD_MEMORY_CITATION = RouteNames.PATCHOULI_RECORD_MEMORY_CITATION
    WARMUP_MODELS = RouteNames.PATCHOULI_WARMUP_MODELS
    MODELS_READY = RouteNames.PATCHOULI_MODELS_READY
