"""通过 GlobalSystemBus 暴露的 Patchouli 公开路由。"""

from hivememory.system.contracts.route_names import RouteNames


class PatchouliRoutes:
    MEMORY_CREATE = RouteNames.PATCHOULI_MEMORY_CREATE
    MEMORY_LIST = RouteNames.PATCHOULI_MEMORY_LIST
    MEMORY_GET = RouteNames.PATCHOULI_MEMORY_GET
    MEMORY_UPDATE = RouteNames.PATCHOULI_MEMORY_UPDATE
    MEMORY_DELETE = RouteNames.PATCHOULI_MEMORY_DELETE
    MEMORY_RECORD_FEEDBACK = RouteNames.PATCHOULI_MEMORY_RECORD_FEEDBACK
    MEMORY_TASK_LIST = RouteNames.PATCHOULI_MEMORY_TASK_LIST
    MEMORY_TASK_GET = RouteNames.PATCHOULI_MEMORY_TASK_GET
    MEMORY_TASK_CANCEL = RouteNames.PATCHOULI_MEMORY_TASK_CANCEL
    AGENT_PROFILE_CREATE = RouteNames.PATCHOULI_AGENT_PROFILE_CREATE
    AGENT_PROFILE_LIST = RouteNames.PATCHOULI_AGENT_PROFILE_LIST
    TOPIC_LIST_ACTIVE = RouteNames.PATCHOULI_TOPIC_LIST_ACTIVE
    TOPIC_GET_DATA = RouteNames.PATCHOULI_TOPIC_GET_DATA
    MEMORY_RETRIEVE = RouteNames.PATCHOULI_MEMORY_RETRIEVE
    MEMORY_RETRIEVE_BY_ALIASES = RouteNames.PATCHOULI_MEMORY_RETRIEVE_BY_ALIASES
    GET_AGENT_PROFILE = RouteNames.PATCHOULI_GET_AGENT_PROFILE
    GET_AGENT_PROFILE_SNAPSHOT = RouteNames.PATCHOULI_GET_AGENT_PROFILE_SNAPSHOT
    MEMORY_READ = RouteNames.PATCHOULI_MEMORY_READ
    INTERACTION_SUBMIT = RouteNames.PATCHOULI_INTERACTION_SUBMIT
    MEMORY_INTENT_SUBMIT = RouteNames.PATCHOULI_MEMORY_INTENT_SUBMIT
    PREPARE_AGENT_RUN = RouteNames.PATCHOULI_PREPARE_AGENT_RUN
    FINALIZE_AGENT_RUN = RouteNames.PATCHOULI_FINALIZE_AGENT_RUN
    CLEANUP_PREPARED_AGENT_RUN = RouteNames.PATCHOULI_CLEANUP_PREPARED_AGENT_RUN
    MANUAL_SETTLE_TOPIC = RouteNames.PATCHOULI_MANUAL_SETTLE_TOPIC
    EVICT_TOPIC = RouteNames.PATCHOULI_EVICT_TOPIC
    RECORD_MEMORY_CITATION = RouteNames.PATCHOULI_RECORD_MEMORY_CITATION
    WARMUP_MODELS = RouteNames.PATCHOULI_WARMUP_MODELS
    MODELS_READY = RouteNames.PATCHOULI_MODELS_READY
