"""Patchouli public routes exposed through GlobalSystemBus."""

from hivememory.system.contracts.route_names import RouteNames


class PatchouliRoutes:
    PASSIVE_ANALYZE_AND_RETRIEVE = RouteNames.PATCHOULI_PASSIVE_ANALYZE_AND_RETRIEVE
    SUBMIT_INTERACTION = RouteNames.PATCHOULI_SUBMIT_INTERACTION
    MEMORY_RETRIEVE = RouteNames.PATCHOULI_MEMORY_RETRIEVE
    MEMORY_RETRIEVE_BY_ALIASES = RouteNames.PATCHOULI_MEMORY_RETRIEVE_BY_ALIASES
    GET_AGENT_PROFILE = RouteNames.PATCHOULI_GET_AGENT_PROFILE
    PREPARE_AGENT_RUN = RouteNames.PATCHOULI_PREPARE_AGENT_RUN
    FINALIZE_AGENT_RUN = RouteNames.PATCHOULI_FINALIZE_AGENT_RUN
    CLEANUP_PREPARED_AGENT_RUN = RouteNames.PATCHOULI_CLEANUP_PREPARED_AGENT_RUN
    MANUAL_ARCHIVE_TOPIC = RouteNames.PATCHOULI_MANUAL_ARCHIVE_TOPIC
    RECORD_MEMORY_CITATION = RouteNames.PATCHOULI_RECORD_MEMORY_CITATION
