"""子系统路由视图与全局路由视图共享的规范公开路由名。"""


class RouteNames:
    """公开 GlobalSystemBus 路由字符串的唯一事实来源。"""

    GATEWAY_PROCESS = "gateway.public.process"

    PATCHOULI_MEMORY_CREATE = "patchouli.public.memory.create"
    PATCHOULI_MEMORY_LIST = "patchouli.public.memory.list"
    PATCHOULI_MEMORY_GET = "patchouli.public.memory.get"
    PATCHOULI_MEMORY_UPDATE = "patchouli.public.memory.update"
    PATCHOULI_MEMORY_DELETE = "patchouli.public.memory.delete"
    PATCHOULI_MEMORY_RECORD_FEEDBACK = "patchouli.public.memory.record_feedback"
    PATCHOULI_MEMORY_TASK_LIST = "patchouli.public.memory_task.list"
    PATCHOULI_MEMORY_TASK_GET = "patchouli.public.memory_task.get"
    PATCHOULI_MEMORY_TASK_CANCEL = "patchouli.public.memory_task.cancel"
    PATCHOULI_AGENT_PROFILE_CREATE = "patchouli.public.agent_profile.create"
    PATCHOULI_AGENT_PROFILE_LIST = "patchouli.public.agent_profile.list"
    PATCHOULI_TOPIC_LIST_ACTIVE = "patchouli.public.topic.list_active"
    PATCHOULI_TOPIC_GET_DATA = "patchouli.public.topic.get_data"
    PATCHOULI_MEMORY_RETRIEVE = "patchouli.public.memory.retrieve"
    PATCHOULI_MEMORY_RETRIEVE_BY_ALIASES = "patchouli.public.memory.retrieve_by_aliases"
    PATCHOULI_GET_AGENT_PROFILE = "patchouli.public.get_agent_profile"
    PATCHOULI_GET_AGENT_PROFILE_SNAPSHOT = "patchouli.public.get_agent_profile_snapshot"
    PATCHOULI_MEMORY_READ = "patchouli.public.memory.read"
    PATCHOULI_INTERACTION_SUBMIT = "patchouli.public.interaction.submit"
    PATCHOULI_MEMORY_INTENT_SUBMIT = "patchouli.public.memory_intent.submit"
    PATCHOULI_PREPARE_AGENT_RUN = "patchouli.public.prepare_agent_run"
    PATCHOULI_FINALIZE_AGENT_RUN = "patchouli.public.finalize_agent_run"
    PATCHOULI_CLEANUP_PREPARED_AGENT_RUN = "patchouli.public.cleanup_prepared_agent_run"
    PATCHOULI_MANUAL_SETTLE_TOPIC = "patchouli.public.manual_settle_topic"
    PATCHOULI_EVICT_TOPIC = "patchouli.public.evict_topic"
    PATCHOULI_RECORD_MEMORY_CITATION = "patchouli.public.record_memory_citation"
    PATCHOULI_WARMUP_MODELS = "patchouli.public.models.warmup"
    PATCHOULI_MODELS_READY = "patchouli.public.models.ready"

    ALICE_RUN_AGENT = "alice.public.run_agent"
    ALICE_RUN_AGENT_STREAM = "alice.public.run_agent_stream"
