"""Global route constants for public cross-subsystem APIs."""

from hivememory.system.contracts.route_names import RouteNames


class GlobalRoutes:
    """Routes that are accessible through GlobalSystemBus."""

    PATCHOULI_PASSIVE_ANALYZE_AND_RETRIEVE = RouteNames.PATCHOULI_PASSIVE_ANALYZE_AND_RETRIEVE
    PATCHOULI_SUBMIT_INTERACTION = RouteNames.PATCHOULI_SUBMIT_INTERACTION
    PATCHOULI_MEMORY_RETRIEVE = RouteNames.PATCHOULI_MEMORY_RETRIEVE
    PATCHOULI_MEMORY_RETRIEVE_BY_ALIASES = RouteNames.PATCHOULI_MEMORY_RETRIEVE_BY_ALIASES
    PATCHOULI_GET_AGENT_PROFILE = RouteNames.PATCHOULI_GET_AGENT_PROFILE
    PATCHOULI_PREPARE_AGENT_RUN = RouteNames.PATCHOULI_PREPARE_AGENT_RUN
    PATCHOULI_FINALIZE_AGENT_RUN = RouteNames.PATCHOULI_FINALIZE_AGENT_RUN
    PATCHOULI_CLEANUP_PREPARED_AGENT_RUN = RouteNames.PATCHOULI_CLEANUP_PREPARED_AGENT_RUN
    PATCHOULI_MANUAL_ARCHIVE_TOPIC = RouteNames.PATCHOULI_MANUAL_ARCHIVE_TOPIC
    PATCHOULI_RECORD_MEMORY_CITATION = RouteNames.PATCHOULI_RECORD_MEMORY_CITATION

    ALICE_RUN_AGENT = RouteNames.ALICE_RUN_AGENT
    ALICE_RUN_AGENT_STREAM = RouteNames.ALICE_RUN_AGENT_STREAM
