"""Global route constants for public cross-subsystem APIs."""

from hivememory.system.contracts.route_names import RouteNames


class GlobalRoutes:
    """Routes that are accessible through GlobalSystemBus."""

    PATCHOULI_PASSIVE_ANALYZE_AND_RETRIEVE = RouteNames.PATCHOULI_PASSIVE_ANALYZE_AND_RETRIEVE
    PATCHOULI_SUBMIT_INTERACTION = RouteNames.PATCHOULI_SUBMIT_INTERACTION
    PATCHOULI_MEMORY_CREATE = RouteNames.PATCHOULI_MEMORY_CREATE
    PATCHOULI_MEMORY_LIST = RouteNames.PATCHOULI_MEMORY_LIST
    PATCHOULI_MEMORY_GET = RouteNames.PATCHOULI_MEMORY_GET
    PATCHOULI_MEMORY_UPDATE = RouteNames.PATCHOULI_MEMORY_UPDATE
    PATCHOULI_MEMORY_DELETE = RouteNames.PATCHOULI_MEMORY_DELETE
    PATCHOULI_MEMORY_RECORD_FEEDBACK = RouteNames.PATCHOULI_MEMORY_RECORD_FEEDBACK
    PATCHOULI_MEMORY_TASK_LIST = RouteNames.PATCHOULI_MEMORY_TASK_LIST
    PATCHOULI_MEMORY_TASK_GET = RouteNames.PATCHOULI_MEMORY_TASK_GET
    PATCHOULI_MEMORY_TASK_CANCEL = RouteNames.PATCHOULI_MEMORY_TASK_CANCEL
    PATCHOULI_AGENT_PROFILE_CREATE = RouteNames.PATCHOULI_AGENT_PROFILE_CREATE
    PATCHOULI_AGENT_PROFILE_LIST = RouteNames.PATCHOULI_AGENT_PROFILE_LIST
    PATCHOULI_TOPIC_LIST_ACTIVE = RouteNames.PATCHOULI_TOPIC_LIST_ACTIVE
    PATCHOULI_MEMORY_RETRIEVE = RouteNames.PATCHOULI_MEMORY_RETRIEVE
    PATCHOULI_MEMORY_RETRIEVE_BY_ALIASES = RouteNames.PATCHOULI_MEMORY_RETRIEVE_BY_ALIASES
    PATCHOULI_GET_AGENT_PROFILE = RouteNames.PATCHOULI_GET_AGENT_PROFILE
    PATCHOULI_PREPARE_AGENT_RUN = RouteNames.PATCHOULI_PREPARE_AGENT_RUN
    PATCHOULI_FINALIZE_AGENT_RUN = RouteNames.PATCHOULI_FINALIZE_AGENT_RUN
    PATCHOULI_CLEANUP_PREPARED_AGENT_RUN = RouteNames.PATCHOULI_CLEANUP_PREPARED_AGENT_RUN
    PATCHOULI_MANUAL_SETTLE_TOPIC = RouteNames.PATCHOULI_MANUAL_SETTLE_TOPIC
    PATCHOULI_EVICT_TOPIC = RouteNames.PATCHOULI_EVICT_TOPIC
    PATCHOULI_RECORD_MEMORY_CITATION = RouteNames.PATCHOULI_RECORD_MEMORY_CITATION
    PATCHOULI_WARMUP_MODELS = RouteNames.PATCHOULI_WARMUP_MODELS
    PATCHOULI_MODELS_READY = RouteNames.PATCHOULI_MODELS_READY

    ALICE_RUN_AGENT = RouteNames.ALICE_RUN_AGENT
    ALICE_RUN_AGENT_STREAM = RouteNames.ALICE_RUN_AGENT_STREAM
