blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/artemis03976/HiveMemory/docs
    about: 请查阅项目文档了解更多信息
  - name: Discussion
    url: https://github.com/artemis03976/HiveMemory/discussions
    about: 有问题或想讨论？来参与社区讨论吧！
