import type { MemoryGenerationTask } from '@/types/memoryTask';

// Mock data for development/testing when the memory task backend is not available.
export const MOCK_MEMORY_TASKS: MemoryGenerationTask[] = [
  {
    task_id: 'mock-memory-task-running-write',
    topic_id: 'mock-topic-current',
    label: '从当前对话中生成新记忆',
    source: 'WRITE',
    pending_alias: 'fact_runtime_window_first_pass',
    status: 'running',
    canonical_alias: null,
    error: null,
    created_at: '2026-06-11T09:16:20Z',
    started_at: '2026-06-11T09:16:24Z',
    finished_at: null,
    cancel_requested: false,
    cancelled: false,
    reason: null,
  },
  {
    task_id: 'mock-memory-task-pending-merge',
    topic_id: 'mock-topic-current',
    label: '合并相似记忆候选',
    source: 'MERGE',
    pending_alias: 'merged_ui_store_refactor_notes',
    status: 'pending',
    canonical_alias: null,
    error: null,
    created_at: '2026-06-11T09:15:02Z',
    started_at: null,
    finished_at: null,
    cancel_requested: false,
    cancelled: false,
    reason: 'queued_after_chat_run',
  },
  {
    task_id: 'mock-memory-task-cancelling-update',
    topic_id: 'mock-topic-ui',
    label: '更新 Memory Runtime Window 的实现细节',
    source: 'UPDATE',
    pending_alias: 'code_memory_runtime_window',
    status: 'running',
    canonical_alias: 'code_memory_runtime_window_v1',
    error: null,
    created_at: '2026-06-11T09:13:43Z',
    started_at: '2026-06-11T09:13:47Z',
    finished_at: null,
    cancel_requested: true,
    cancelled: false,
    reason: 'user_requested',
  },
  {
    task_id: 'mock-memory-task-completed-write',
    topic_id: 'mock-topic-ui',
    label: '记录 store 分域重构结论',
    source: 'WRITE',
    pending_alias: 'fact_zustand_store_refactor_strategy',
    status: 'completed',
    canonical_alias: 'fact_zustand_store_refactor_strategy',
    error: null,
    created_at: '2026-06-11T08:58:12Z',
    started_at: '2026-06-11T08:58:15Z',
    finished_at: '2026-06-11T08:58:39Z',
    cancel_requested: false,
    cancelled: false,
    reason: null,
  },
  {
    task_id: 'mock-memory-task-cancelled-archive',
    topic_id: 'mock-topic-cleanup',
    label: '归档过期调试记忆',
    source: 'ARCHIVE',
    pending_alias: 'debug_old_kernel_store_notes',
    status: 'cancelled',
    canonical_alias: null,
    error: null,
    created_at: '2026-06-11T08:41:08Z',
    started_at: '2026-06-11T08:41:15Z',
    finished_at: '2026-06-11T08:42:01Z',
    cancel_requested: true,
    cancelled: true,
    reason: 'user_requested',
  },
  {
    task_id: 'mock-memory-task-failed-split',
    topic_id: 'mock-topic-memory',
    label: '拆分过长的架构记忆',
    source: 'SPLIT',
    pending_alias: 'doc_hivememory_architecture_long_note',
    status: 'failed',
    canonical_alias: null,
    error: 'Split candidate exceeded maximum section depth; manual review required.',
    created_at: '2026-06-11T08:22:30Z',
    started_at: '2026-06-11T08:22:33Z',
    finished_at: '2026-06-11T08:23:11Z',
    cancel_requested: false,
    cancelled: false,
    reason: 'validation_failed',
  },
  {
    task_id: 'mock-memory-task-completed-update-no-alias',
    topic_id: '',
    label: '同步无话题后台记忆维护任务',
    source: 'UPDATE',
    pending_alias: null,
    status: 'completed',
    canonical_alias: null,
    error: null,
    created_at: '2026-06-11T07:59:00Z',
    started_at: '2026-06-11T07:59:06Z',
    finished_at: '2026-06-11T07:59:28Z',
    cancel_requested: false,
    cancelled: false,
    reason: 'background_maintenance',
  },
];
