"""
HiveMemory 核心数据模型

重导出记忆、智能体、交互流转等领域模型，以保持向下兼容性。
"""

from .artifact import (
    ArtifactType,
    ArtifactRef,
    BaseArtifact,
    InteractionTurnSnapshot,
    InteractionArtifact,
    DocumentLocator,
    DocumentArtifact,
    MemoryInputRef,
    MemoryVersionSnapshot,
    MemoryCreationArtifact,
    MemoryVersionArtifact,
    MemoryEventType,
    MemoryEventLog,
)
from .memory import (
    MemoryType,
    MemoryVisibility,
    VerificationStatus,
    MetaData,
    IndexLayer,
    Artifacts,
    PayloadLayer,
    RelationLayer,
    MemoryAtom,
)
from .interaction import (
    ActionReducer,
    TraceReducer,
    Identity,
    StreamMessageType,
    StreamMessage,
    TurnEvent,
    AgentAction,
    TraceItem,
    TurnRecord,
    TopicSnapshot,
)
from .agent import (
    AgentProfile,
    OMNI_DOLL_PROFILE,
)
from .model_definition import ModelDefinition
from .pending import (
    PendingAtomStatus,
    PendingAtomResolution,
    PendingAtomSnapshot,
    is_legal_transition,
    allowed_transitions,
    InvalidStateTransition,
    WriteFocus,
    UpdateFocus,
    RuntimeScope,
    PendingAtom,
    PendingAtomSettlement,
)

__all__ = [
    "ArtifactType",
    "ArtifactRef",
    "BaseArtifact",
    "InteractionTurnSnapshot",
    "InteractionArtifact",
    "DocumentLocator",
    "DocumentArtifact",
    "MemoryInputRef",
    "MemoryVersionSnapshot",
    "MemoryCreationArtifact",
    "MemoryVersionArtifact",
    "MemoryEventType",
    "MemoryEventLog",
    "MemoryType",
    "MemoryVisibility",
    "VerificationStatus",
    "MetaData",
    "IndexLayer",
    "Artifacts",
    "PayloadLayer",
    "RelationLayer",
    "MemoryAtom",
    "ActionReducer",
    "TraceReducer",
    "Identity",
    "StreamMessageType",
    "StreamMessage",
    "TurnEvent",
    "AgentAction",
    "TraceItem",
    "TurnRecord",
    "TopicSnapshot",
    "AgentProfile",
    "OMNI_DOLL_PROFILE",
    "ModelDefinition",
    "PendingAtomStatus",
    "PendingAtomResolution",
    "PendingAtomSnapshot",
    "is_legal_transition",
    "allowed_transitions",
    "InvalidStateTransition",
    "WriteFocus",
    "UpdateFocus",
    "RuntimeScope",
    "PendingAtom",
    "PendingAtomSettlement",
]
